language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x

env:
  global:
    - GO111MODULE: "on"

install:
  - make install-dependencies
  - make install-tools
  - make install

script:
  - make lint
  - make test-verbose-with-coverage
  - gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci; fi
